name: coolercodonopt

channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - ipykernel=5.4
  - python=3.9
  - ipython=7.19
  - numpy=1.19
  - pandas=1.2
  - pip=21.0
  - pip:
    - dnachisel==3.2.6
  - jupyterlab=3.0
  - biopython=1.78
