#!/bin/bash
#
#SBATCH --job-name=score
#SBATCH --output=score.out
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --time=15:00

# This script runs optimize.py 50 times and outputs the score of each run

module load python/3.7.0

source /home/guzmanfj/novoproteins/venv/bin/activate

for i in {0..6}
    do
        python /home/guzmanfj/novoproteins/scripts/optimize.py GGCGCTGGGCGTTTCGCCCCCCGTGTCGCCTGCACAAGGGCGACATGCTACGTGAAACGCAAGGATCGTTACGTGGTGTCCATGCCTATCCCCGAGCCGGATCGGACATCGGAGCCCGACTCCGAGCCGATGCGGCCCATCCAAAGCCCACGTGTCGCCCTCGTTGCGACCGAGACGTCGCGCTGCGCGAGGCCTACTCCTTGTGGGCCCCACCGGCTGCGTATACGACCGGAGGTGGGGCCCCGCCGCGTTAAATTCCGCGCCTCCGCGGCGCCTGACCTCGAGTGGATGAAAATGCCCGTTTTGCCCCTCCTGTCACTACGGTGCCACGTCTCAGTTGCCTCGGCAAGACGTGGGTCCAGGGGGCGTGGTCCACGTGAGCCGGACGTGGCTTGGATGGGCATTCCGAGTTGGGACCCACATGTCAGTATAGGAGCGTCCGTGGGCAACGCAAGCGCCGACGCCAAGGGCTGTCCAAGAGATGCCACCGATAATGTGCTCGAGCAAGGACTAGAGCACTTGCGTCTGTGCAATCGTGAGACAAAGCTCCACCAGAGATCATGGACGATTGCCAACCTACGTAGTGGCCGTGTCAAACGCAGTGCCAACTTCCTGAAGCTGTCCCGCGCGAAC -vv --atg | tail -n 1 >> scores.txt
    done

deactivate

module unload python/3.7.0

